# ==============================================================================
# DOCKER COMPOSE ДЛЯ УДАЛЕННОГО СЕРВЕРА
# ==============================================================================
# Запускает: База данных + Backend + Telegram Bot
# Используется на удаленном сервере
# 
# Запуск: docker-compose -f docker-compose.server.yml --env-file .env up -d
# Остановка: docker-compose -f docker-compose.server.yml --env-file .env down
# Логи: docker-compose -f docker-compose.server.yml --env-file .env logs -f

version: '3.8'

services:
  # ==============================================================================
  # БАЗА ДАННЫХ (PostgreSQL с PostGIS)
  # ==============================================================================
  db:
    image: postgis/postgis:15-3.3
    container_name: social_rent_db
    restart: unless-stopped
    
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
    ports:
      - "${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}"
      
    volumes:
      - social_rent_postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
    networks:
      - social_rent_network
      
    # Health check для проверки готовности базы данных
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  # ==============================================================================
  # BACKEND (FastAPI)
  # ==============================================================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: social_rent_backend
    restart: unless-stopped
    
    environment:
      # Подключение к базе данных
      DATABASE_URL: ${DATABASE_URL_INTERNAL}
      
      # Telegram настройки
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
      BACKEND_URL: ${BACKEND_URL}
      
      # API настройки
      API_PREFIX: ${API_PREFIX}
      HOST: ${BACKEND_HOST}
      PORT: ${BACKEND_PORT}
      
      # Безопасность и CORS
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      
      # Окружение
      ENVIRONMENT: ${ENVIRONMENT}
      LOG_LEVEL: ${LOG_LEVEL}
      
      # Тестовые данные
      GENERATE_TEST_DATA: ${GENERATE_TEST_DATA}
      
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      
    depends_on:
      - db
        
    volumes:
      - ./backend:/app
      
    networks:
      - social_rent_network

  # ==============================================================================
  # TELEGRAM BOT
  # ==============================================================================
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: social_rent_bot
    restart: unless-stopped
    
    environment:
      # Telegram настройки
      BOT_TOKEN: ${BOT_TOKEN}
      WEBAPP_URL: ${WEBAPP_URL}
      
      # Подключение к базе данных
      DATABASE_URL: ${DATABASE_URL_INTERNAL}
      
      # Подключение к backend
      BACKEND_URL: http://backend:${BACKEND_PORT}
      
      # Окружение
      ENVIRONMENT: ${ENVIRONMENT}
      LOG_LEVEL: ${LOG_LEVEL}
      
    depends_on:
      - db
      - backend
        
    volumes:
      - ./bot:/app
      
    networks:
      - social_rent_network

# ==============================================================================
# VOLUMES
# ==============================================================================
volumes:
  social_rent_postgres_data:
    name: ${POSTGRES_VOLUME_NAME}

# ==============================================================================
# NETWORKS  
# ==============================================================================
networks:
  social_rent_network:
    name: ${DOCKER_NETWORK_NAME}
    driver: bridge