# ==============================================================================
# DOCKER COMPOSE ДЛЯ ЛОКАЛЬНОЙ МАШИНЫ
# ==============================================================================
# Запускает: Frontend приложение
# Используется на локальной машине для разработки
# Подключается к удаленному backend серверу
# 
# Запуск: docker-compose -f docker-compose.local.yml --env-file .env up -d
# Остановка: docker-compose -f docker-compose.local.yml --env-file .env down
# Логи: docker-compose -f docker-compose.local.yml --env-file .env logs -f

version: '3.8'

services:
  # ==============================================================================
  # FRONTEND (React)
  # ==============================================================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: social_rent_frontend
    restart: unless-stopped
    
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      
    environment:
      # Backend API конфигурация
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
      REACT_APP_BOT_USERNAME: ${REACT_APP_BOT_USERNAME}
      
      # Development настройки
      HOST: 0.0.0.0
      PORT: ${FRONTEND_PORT}
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
      
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
    networks:
      - frontend_network

# ==============================================================================
# NETWORKS  
# ==============================================================================
networks:
  frontend_network:
    driver: bridge